from datetime import datetime

def generate_email_subject():
    """Create a subject line with the current date."""
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d %H:%M")
    return f"Job Postings as of {date_str}"

def generate_email_timestamp():
    """Return a readable timestamp for the email footer."""
    now = datetime.now()
    return now.strftime("%A, %B %d, %Y at %I:%M %p")

def format_email_html(jobs_by_company, previous_jobs=None):
    """
    Generate an HTML email string from a list of jobs grouped by company.

    jobs_by_company: list of dicts like
    [
        {
            "company": "Home Depot",
            "company_url": "https://careers.homedepot.ca",
            "jobs": [
                {"title": "Sales Associate", "link": "...", "location": "..."},
                ...
            ]
        },
        ...
    ]

    previous_jobs: optional flat list of job dicts, each with 'company', representing jobs from a previous run. Used to determine which current jobs are new (for highlighting) and which previously-seen jobs are no longer posted (for the removal list).
    """
    
    html_parts = [
        "<html>",
        "<body>",
        "<h2>Job-a-Doodle-Doo 🐔 Job Listings</h2>"
    ]
    
    timestamp = generate_email_timestamp()
    html_parts.append(f"<p size='small'><em>As of {timestamp}</em></p>")
    
    previous_links = set(job['link'] for job in previous_jobs) if previous_jobs else set()
    current_links = set(job['link'] for entry in jobs_by_company for job in entry['jobs'])
    removed_links = previous_links - current_links
    previous_jobs_by_link = {job['link']: job for job in previous_jobs} if previous_jobs else {}

    for entry in jobs_by_company:
        company = entry["company"]
        company_url = entry.get("company_jobs_url", "#")
        html_parts.append(f'<h3><a href="{company_url}">{company}</a></h3>')

        if not entry["jobs"]:
            html_parts.append("<p>No jobs found.</p>")
            continue

        html_parts.append("<ul>")
        for job in entry["jobs"]:
            job_title = job["title"]
            job_link = job.get("link", "#")
            location = job.get("location", "")
            # Highlight new jobs
            if previous_jobs is not None and job['link'] not in previous_links:
                html_parts.append(f'<li>⭐⭐ <a href="{job_link}">{job_title}</a> ({location}) ⭐⭐</li>')
            else:
                html_parts.append(f'<li><a href="{job_link}">{job_title}</a> ({location})</li>')
        html_parts.append("</ul>")


    html_parts.append("<hr><h3>Jobs that are No Longer Posted</h3>")
    if removed_links:
        html_parts.append("<p><em>Note: the links below may no longer be active.</em></p>")
        html_parts.append("<ul>")
        for link in removed_links:
            prev_job = previous_jobs_by_link.get(link)
            if prev_job:
                title = prev_job.get('title', 'Unknown Title')
                location = prev_job.get('location', '')
                company_name = prev_job.get('company', 'Unknown Company')
                html_parts.append(
                    f"<li><strong>{company_name}</strong>: <a href='{link}'>{title}</a> ({location})</li>"
                )
            else:
                html_parts.append(f"<li><a href='{link}'>{link}</a></li>")
        html_parts.append("</ul>")
    else:
        html_parts.append("<p>No jobs were removed since the last update.</p>")
 

    html_parts.extend([
        "<hr>",
        "<p><em>This email was generated by Job-a-Doodle-Doo 🐔</em></p>",
        "</body>",
        "</html>"
    ])

    return "\n".join(html_parts)
