def format_email_text(jobs_by_company):
    """
    jobs_by_company: list of dicts like
    [
        {"company": "Home Depot", "jobs": [{"title": ..., "link": ..., "location": ...}, ...]},
        ...
    ]
    """
    lines = []
    for entry in jobs_by_company:
        lines.append(f"\n=== {entry['company']} ===")
        for job in entry["jobs"]:
            lines.append(f"- {job['title']} → {job['link']} ({job['location']})")
    return "\n".join(lines)



def format_email_html(jobs_by_company, timestamp=None):
    """
    Generate an HTML email string from a list of jobs grouped by company.

    jobs_by_company: list of dicts like
    [
        {
            "company": "Home Depot",
            "company_url": "https://careers.homedepot.ca",
            "jobs": [
                {"title": "Sales Associate", "link": "...", "location": "..."},
                ...
            ]
        },
        ...
    ]
    """
    html_parts = [
        "<html>",
        "<body>",
        "<h2>Job Listings</h2>"
    ]
    
    if timestamp:
        html_parts.append(f"<p size='small'><em>As of {timestamp}</em></p>")

    for entry in jobs_by_company:
        print(f"Formatting jobs for {entry}...")
        company = entry["company"]
        company_url = entry.get("company_jobs_url", "#")
        html_parts.append(f'<h3><a href="{company_url}">{company}</a></h3>')
        
        if not entry["jobs"]:
            html_parts.append("<p>No jobs found.</p>")
            continue

        html_parts.append("<ul>")
        for job in entry["jobs"]:
            job_title = job["title"]
            job_link = job.get("link", "#")
            location = job.get("location", "")
            html_parts.append(
                f'<li><a href="{job_link}">{job_title}</a> ({location})</li>'
            )
        html_parts.append("</ul>")

    html_parts.extend([
        "<p>Generated by Job-a-Doodle-Doo 🐔</p>",
        "</body>",
        "</html>"
    ])

    return "\n".join(html_parts)
